volumes:
  server-data:
    driver: local

services:
  app:
    build: .
    container_name: task_queue_001
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./var:/srv/var
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  # This service could be accessed by port 8081 as local Telegram Bot API server.
  telegram-bot-api:
    image: ghcr.io/bots-house/docker-telegram-bot-api:latest
    container_name: telegram-bot-api
    hostname: telegram-bot-api
    command: "--dir=/var/lib/telegram-bot-api"
    volumes:
      - server-data:/var/lib/telegram-bot-api
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
